# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Murex-Base
version:      0.06
version_from: lib/Murex/Base.pm
installdirs:  site
requires:
    Data::Dumper::Simple:          Log::Dispatch
    English:                       Template
    Hash::Merge:                   Digest::MD5
    Log::Dispatch::FileRotate:     Log::Log4perl
    Mail::Sendmail:                Log::Dispatch::Email
    XML::Simple:                   Crypt::RC6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
